feat: add check-strongswan-connexion.rb plugin
sensu-plugins/sensu-plugins-strongswan pull request #4
Opened 2018-02-21 14:39 UTC by nishiki

## Pull Request Checklist

Hi,

I created a new plugin to check the status for one ipsec connection.
I use this plugin on my production environment, and i wanted to shared it with you

Regards,

#### General

- [X] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [X] RuboCop passes

- [X] Existing tests pass

#### New Plugins

- [ ] Tests

- [X] Add the plugin to the README

- [X] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Purpose

#### Known Compatability Issues

2018-02-22 07:34 UTC, majormoses commented
Thanks for your contribution to Sensu plugins! Without people like you submitting PRs we couldn't run the project. I will review it shortly.

2018-02-22 07:38 UTC, majormoses requested changes
Overall I think this looks great can you enhance the changelog entry and provide a [testing artifact](https://github.com/sensu-plugins/community/blob/master/PULL_REQUEST_PROCESS.md#7-testing-artifacts) which can be a simple showing the script input and output.

2018-02-22 07:38 UTC, majormoses commented on CHANGELOG.md
> +- add check-strongswan-connection.rb plugin
a bit better description would be ideal something like:
```
### Added
check-strongswan-connection.rb: checks the health of a strongwan connection (@nishiki)
```

2018-02-22 08:55 UTC, nishiki commented
Hello,

Thanks for your review.

Below the output of my manual tests
```
# /opt/sensu/embedded/bin/ruby check-strongswan-connection.rb --connection dc-fr-pa2
CheckStrongswanConnection OK: the connection dc-fr-pa2 is up
# /opt/sensu/embedded/bin/ruby check-strongswan-connection.rb --connection dc-fr-th3
CheckStrongswanConnection CRITICAL: the connection dc-fr-th3 is down
# /opt/sensu/embedded/bin/ruby check-strongswan-connection.rb --connection  dc-fr-pa666
CheckStrongswanConnection WARNING: the connection dc-fr-pa666 doesn't exist
```

2018-02-23 01:39 UTC, majormoses approved these changes

2018-02-23 01:40 UTC, merged

2018-02-23 01:47 UTC, majormoses commented
released: https://rubygems.org/gems/sensu-plugins-strongswan/versions/1.1.0

2018-02-23 07:34 UTC, nishiki commented
Great, thanks!